kind: pipeline
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
  - name: test
    image: golang
    commands:
      - cd parser
      - go test ./... -race

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - cd parser
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag
